/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "bbox_data_model.h"
#include "bbox_data_milan.h"
#include "bbox_file_list.h"
#include "bbox_rdr_pub.h"

DEFINE_DATA_MODEL(TEE);
DEFINE_DATA_MODEL(TF);
DEFINE_DATA_MODEL(DRIVER);
DEFINE_DATA_MODEL(DVPP);
DEFINE_DATA_MODEL(TS);
DEFINE_DATA_MODEL(TS_START);
DEFINE_DATA_MODEL(TS_LOG);
DEFINE_DATA_MODEL(DEVICE_OS_LOG);
DEFINE_DATA_MODEL(DEVICE_FW_LOG);
DEFINE_DATA_MODEL(RUN_EVENT_LOG);
DEFINE_DATA_MODEL(SEC_LOG);
DEFINE_DATA_MODEL(BIOS);
DEFINE_DATA_MODEL(BIOS_SRAM);
DEFINE_DATA_MODEL(LPM);
DEFINE_DATA_MODEL(LPM_START);
DEFINE_DATA_MODEL(HSM);
DEFINE_DATA_MODEL(HSM_START);
DEFINE_DATA_MODEL(HSM_LOG);
DEFINE_DATA_MODEL(NETWORK);
DEFINE_DATA_MODEL(LPM_LOG);
DEFINE_DATA_MODEL(IMU_BOOT_LOG);
DEFINE_DATA_MODEL(UEFI_BOOT_LOG);
DEFINE_DATA_MODEL(IMU_RUN_LOG);
DEFINE_DATA_MODEL(DP);

/* HDR */
DEFINE_DATA_MODEL(HDR_BOOT_BIOS);
DEFINE_DATA_MODEL(HDR_BOOT_DDR);
DEFINE_DATA_MODEL(HDR_BOOT_TEE);
DEFINE_DATA_MODEL(HDR_BOOT_HSM);
DEFINE_DATA_MODEL(HDR_BOOT_ATF);
DEFINE_DATA_MODEL(HDR_BOOT_AREA);
DEFINE_DATA_MODEL(HDR_BOOT);
DEFINE_DATA_MODEL(HDR_RUN_OS);
DEFINE_DATA_MODEL(HDR_RUN_LPM);
DEFINE_DATA_MODEL(HDR_RUN_TEE);
DEFINE_DATA_MODEL(HDR_RUN_HSM);
DEFINE_DATA_MODEL(HDR_RUN_ATF);
DEFINE_DATA_MODEL(HDR_RUN_AREA);
DEFINE_DATA_MODEL(HDR_RUN);
DEFINE_DATA_MODEL(HDR_LOG);
DEFINE_DATA_MODEL(HDR);
DEFINE_DATA_MODEL(HDR_BOOT_INFO);
DEFINE_DATA_MODEL(HDR_RUN_INFO);
DEFINE_DATA_MODEL(HDR_STATUS_BLOCK_RUN);
DEFINE_DATA_MODEL(HDR_STATUS_BLOCK_BOOT);
DEFINE_DATA_MODEL(HDR_STATUS_BLOCK);
DEFINE_DATA_MODEL(HDR_STATUS_DATA);
DEFINE_DATA_MODEL(HDR_STATUS);

/* CDR */
DEFINE_DATA_MODEL(CDR);
DEFINE_DATA_MODEL(CDR_SRAM);
DEFINE_DATA_MODEL(CDR_FULL);
DEFINE_DATA_MODEL(CDR_MIN);
DEFINE_DATA_MODEL(CDR_LOOSE);
DEFINE_DATA_MODEL(CDR_SRAM_LOOSE);

/* HBM */
DEFINE_DATA_MODEL(HBM_SRAM);

/* SRAM */
DEFINE_DATA_MODEL(SRAM_SNAPSHOT);
DEFINE_DATA_MODEL(BIOS_HISS);
DEFINE_DATA_MODEL(HBOOT);

struct bbox_plaintext_module_map g_plaintext_module_map[] = {
    {BBOX_DRIVER,    PLAINTEXT_TABLE_DRIVER,      PLAINTEXT_TABLE_DRIVER,       PLAINTEXT_TABLE_NONE},
    {BBOX_TS,        PLAINTEXT_TABLE_TS,          PLAINTEXT_TABLE_TS_START,     PLAINTEXT_TABLE_NONE},
    {BBOX_ATF,       PLAINTEXT_TABLE_TF,          PLAINTEXT_TABLE_TF,           PLAINTEXT_TABLE_NONE},
    {BBOX_LPM,       PLAINTEXT_TABLE_LPM,         PLAINTEXT_TABLE_LPM_START,    PLAINTEXT_TABLE_LPM_LOG},
    {BBOX_HSM,       PLAINTEXT_TABLE_HSM,         PLAINTEXT_TABLE_HSM_START,    PLAINTEXT_TABLE_HSM_LOG},
    {BBOX_DVPP,      PLAINTEXT_TABLE_DVPP,        PLAINTEXT_TABLE_DVPP,         PLAINTEXT_TABLE_NONE},
    {BBOX_BIOS,      PLAINTEXT_TABLE_BIOS,        PLAINTEXT_TABLE_BIOS,         PLAINTEXT_TABLE_NONE},
    {BBOX_TEEOS,     PLAINTEXT_TABLE_TEEOS,       PLAINTEXT_TABLE_TEEOS,        PLAINTEXT_TABLE_NONE},
    {BBOX_NETWORK,   PLAINTEXT_TABLE_NETWORK,     PLAINTEXT_TABLE_NETWORK,      PLAINTEXT_TABLE_NONE},
    {BBOX_IMU,       PLAINTEXT_TABLE_IMU_RUN_LOG, PLAINTEXT_TABLE_IMU_RUN_LOG,  PLAINTEXT_TABLE_NONE},
    {BBOX_CORE_MAX,  PLAINTEXT_TABLE_NONE,        PLAINTEXT_TABLE_NONE,         PLAINTEXT_TABLE_NONE},
};

// analysis the data to plaintext, which is from device by hdc.
struct bbox_plaintext_table_map g_plaintext_table_map[] = {
    {PLAINTEXT_TABLE_DP,                            MODEL_VECTOR_SIZE(DP),
        MODEL_VECTOR_OBJECT(DP),                        BBOX_FILE_NAME_KBOX},
    {PLAINTEXT_TABLE_DRIVER,                        MODEL_VECTOR_SIZE(DRIVER),
        MODEL_VECTOR_OBJECT(DRIVER),                    BBOX_FILE_NAME_DRIVER},
    {PLAINTEXT_TABLE_DVPP,                          MODEL_VECTOR_SIZE(DVPP),
        MODEL_VECTOR_OBJECT(DVPP),                      BBOX_FILE_NAME_DVPP},
    {PLAINTEXT_TABLE_TS,                            MODEL_VECTOR_SIZE(TS),
        MODEL_VECTOR_OBJECT(TS),                        BBOX_FILE_NAME_TS},
    {PLAINTEXT_TABLE_TS_START,                      MODEL_VECTOR_SIZE(TS_START),
        MODEL_VECTOR_OBJECT(TS_START),                  BBOX_FILE_NAME_TS},
    {PLAINTEXT_TABLE_TEEOS,                         MODEL_VECTOR_SIZE(TEE),
        MODEL_VECTOR_OBJECT(TEE),                       BBOX_FILE_NAME_TEE},
    {PLAINTEXT_TABLE_TF,                            MODEL_VECTOR_SIZE(TF),
        MODEL_VECTOR_OBJECT(TF),                        BBOX_FILE_NAME_TF},
    {PLAINTEXT_TABLE_BIOS,                          MODEL_VECTOR_SIZE(BIOS),
        MODEL_VECTOR_OBJECT(BIOS),                      BBOX_FILE_NAME_BIOS},
    {PLAINTEXT_TABLE_BIOS_SRAM,                     MODEL_VECTOR_SIZE(BIOS_SRAM),
        MODEL_VECTOR_OBJECT(BIOS_SRAM),                 BBOX_FILE_NAME_BIOS_SRAM},
    {PLAINTEXT_TABLE_LPM,                           MODEL_VECTOR_SIZE(LPM),
        MODEL_VECTOR_OBJECT(LPM),                       BBOX_FILE_NAME_LPM},
    {PLAINTEXT_TABLE_LPM_START,                     MODEL_VECTOR_SIZE(LPM_START),
        MODEL_VECTOR_OBJECT(LPM_START),                 BBOX_FILE_NAME_LPM},
    {PLAINTEXT_TABLE_HSM,                           MODEL_VECTOR_SIZE(HSM),
        MODEL_VECTOR_OBJECT(HSM),                       BBOX_FILE_NAME_HSM},
    {PLAINTEXT_TABLE_HSM_START,                     MODEL_VECTOR_SIZE(HSM_START),
        MODEL_VECTOR_OBJECT(HSM_START),                 BBOX_FILE_NAME_HSM},
    {PLAINTEXT_TABLE_HSM_LOG,                       MODEL_VECTOR_SIZE(HSM_LOG),
        MODEL_VECTOR_OBJECT(HSM_LOG),                   BBOX_FILE_NAME_HSM_LOG},
    {PLAINTEXT_TABLE_NETWORK,                       MODEL_VECTOR_SIZE(NETWORK),
        MODEL_VECTOR_OBJECT(NETWORK),                   BBOX_FILE_NAME_NETWORK},
    {PLAINTEXT_TABLE_TS_LOG,                        MODEL_VECTOR_SIZE(TS_LOG),
        MODEL_VECTOR_OBJECT(TS_LOG),                    BBOX_FILE_NAME_TS_LOG},
    {PLAINTEXT_TABLE_RUN_DEVICE_OS_LOG,             MODEL_VECTOR_SIZE(DEVICE_OS_LOG),
        MODEL_VECTOR_OBJECT(DEVICE_OS_LOG),            BBOX_FILE_NAME_DEV_OS_LOG},
    {PLAINTEXT_TABLE_DEBUG_DEVICE_OS_LOG,           MODEL_VECTOR_SIZE(DEVICE_OS_LOG),
        MODEL_VECTOR_OBJECT(DEVICE_OS_LOG),          BBOX_FILE_NAME_DEV_OS_LOG},
    {PLAINTEXT_TABLE_DEBUG_DEVICE_FW_LOG,           MODEL_VECTOR_SIZE(DEVICE_FW_LOG),
        MODEL_VECTOR_OBJECT(DEVICE_FW_LOG),               BBOX_FILE_NAME_DEBUG_DEV_FW_LOG},
    {PLAINTEXT_TABLE_RUN_EVENT_LOG,                 MODEL_VECTOR_SIZE(RUN_EVENT_LOG),
        MODEL_VECTOR_OBJECT(RUN_EVENT_LOG),             BBOX_FILE_NAME_RUN_EVENT_LOG},
    {PLAINTEXT_TABLE_SEC_DEVICE_OS_LOG,             MODEL_VECTOR_SIZE(SEC_LOG),
        MODEL_VECTOR_OBJECT(SEC_LOG),                   BBOX_FILE_NAME_DEV_OS_LOG},
    {PLAINTEXT_TABLE_LPM_LOG,                       MODEL_VECTOR_SIZE(LPM_LOG),
        MODEL_VECTOR_OBJECT(LPM_LOG),                   BBOX_FILE_NAME_LPM},
    {PLAINTEXT_TABLE_IMU_BOOT_LOG,                  MODEL_VECTOR_SIZE(IMU_BOOT_LOG),
        MODEL_VECTOR_OBJECT(IMU_BOOT_LOG),              BBOX_FILE_NAME_IMU_BOOT},
    {PLAINTEXT_TABLE_UEFI_BOOT_LOG,                 MODEL_VECTOR_SIZE(UEFI_BOOT_LOG),
        MODEL_VECTOR_OBJECT(UEFI_BOOT_LOG),             BBOX_FILE_NAME_UEFI_BOOT},
    {PLAINTEXT_TABLE_IMU_RUN_LOG,                   MODEL_VECTOR_SIZE(IMU_RUN_LOG),
        MODEL_VECTOR_OBJECT(IMU_RUN_LOG),               BBOX_FILE_NAME_IMU_RUN},
    {PLAINTEXT_TABLE_HDR_BOOT_BIOS,                 MODEL_VECTOR_SIZE(HDR_BOOT_BIOS),
        MODEL_VECTOR_OBJECT(HDR_BOOT_BIOS),             BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_BOOT_DDR,                  MODEL_VECTOR_SIZE(HDR_BOOT_DDR),
        MODEL_VECTOR_OBJECT(HDR_BOOT_DDR),              BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_BOOT_TEE,                  MODEL_VECTOR_SIZE(HDR_BOOT_TEE),
        MODEL_VECTOR_OBJECT(HDR_BOOT_TEE),              BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_BOOT_HSM,                  MODEL_VECTOR_SIZE(HDR_BOOT_HSM),
        MODEL_VECTOR_OBJECT(HDR_BOOT_HSM),              BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_BOOT_ATF,                  MODEL_VECTOR_SIZE(HDR_BOOT_ATF),
        MODEL_VECTOR_OBJECT(HDR_BOOT_ATF),              BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_BOOT_AREA,                 MODEL_VECTOR_SIZE(HDR_BOOT_AREA),
        MODEL_VECTOR_OBJECT(HDR_BOOT_AREA),             BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_BOOT,                      MODEL_VECTOR_SIZE(HDR_BOOT),
        MODEL_VECTOR_OBJECT(HDR_BOOT),                  BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_OS,                    MODEL_VECTOR_SIZE(HDR_RUN_OS),
        MODEL_VECTOR_OBJECT(HDR_RUN_OS),                BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_LPM,                   MODEL_VECTOR_SIZE(HDR_RUN_LPM),
        MODEL_VECTOR_OBJECT(HDR_RUN_LPM),               BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_TEE,                   MODEL_VECTOR_SIZE(HDR_RUN_TEE),
        MODEL_VECTOR_OBJECT(HDR_RUN_TEE),               BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_HSM,                   MODEL_VECTOR_SIZE(HDR_RUN_HSM),
        MODEL_VECTOR_OBJECT(HDR_RUN_HSM),               BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_ATF,                   MODEL_VECTOR_SIZE(HDR_RUN_ATF),
        MODEL_VECTOR_OBJECT(HDR_RUN_ATF),               BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_AREA,                  MODEL_VECTOR_SIZE(HDR_RUN_AREA),
        MODEL_VECTOR_OBJECT(HDR_RUN_AREA),              BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN,                       MODEL_VECTOR_SIZE(HDR_RUN),
        MODEL_VECTOR_OBJECT(HDR_RUN),                   BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_LOG,                       MODEL_VECTOR_SIZE(HDR_LOG),
        MODEL_VECTOR_OBJECT(HDR_LOG),                   BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR,                           MODEL_VECTOR_SIZE(HDR),
        MODEL_VECTOR_OBJECT(HDR),                       BBOX_FILE_NAME_HDR},
    {PLAINTEXT_TABLE_HDR_BOOT_INFO,                 MODEL_VECTOR_SIZE(HDR_BOOT_INFO),
        MODEL_VECTOR_OBJECT(HDR_BOOT_INFO),             BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_RUN_INFO,                  MODEL_VECTOR_SIZE(HDR_RUN_INFO),
        MODEL_VECTOR_OBJECT(HDR_RUN_INFO),              BBOX_FILE_NAME_HDR_LOG},
    {PLAINTEXT_TABLE_HDR_STATUS_BLOCK_BOOT,         MODEL_VECTOR_SIZE(HDR_STATUS_BLOCK_BOOT),
        MODEL_VECTOR_OBJECT(HDR_STATUS_BLOCK_BOOT),     BBOX_FILE_NAME_HDR_STATUS},
    {PLAINTEXT_TABLE_HDR_STATUS_BLOCK_RUN,          MODEL_VECTOR_SIZE(HDR_STATUS_BLOCK_RUN),
        MODEL_VECTOR_OBJECT(HDR_STATUS_BLOCK_RUN),      BBOX_FILE_NAME_HDR_STATUS},
    {PLAINTEXT_TABLE_HDR_STATUS_BLOCK,              MODEL_VECTOR_SIZE(HDR_STATUS_BLOCK),
        MODEL_VECTOR_OBJECT(HDR_STATUS_BLOCK),          BBOX_FILE_NAME_HDR_STATUS},
    {PLAINTEXT_TABLE_HDR_STATUS_DATA,               MODEL_VECTOR_SIZE(HDR_STATUS_DATA),
        MODEL_VECTOR_OBJECT(HDR_STATUS_DATA),           BBOX_FILE_NAME_HDR_STATUS},
    {PLAINTEXT_TABLE_HDR_STATUS,                    MODEL_VECTOR_SIZE(HDR_STATUS),
        MODEL_VECTOR_OBJECT(HDR_STATUS),                BBOX_FILE_NAME_HDR_STATUS},
    {PLAINTEXT_TABLE_CDR_FULL,                      MODEL_VECTOR_SIZE(CDR_FULL),
        MODEL_VECTOR_OBJECT(CDR_FULL),                  BBOX_FILE_NAME_CDR_FULL},
    {PLAINTEXT_TABLE_CDR_MIN,                       MODEL_VECTOR_SIZE(CDR_MIN),
        MODEL_VECTOR_OBJECT(CDR_MIN),                   BBOX_FILE_NAME_CDR_FULL},
    {PLAINTEXT_TABLE_CDR,                           MODEL_VECTOR_SIZE(CDR),
        MODEL_VECTOR_OBJECT(CDR),                       BBOX_FILE_NAME_CDR_FULL},
    {PLAINTEXT_TABLE_CDR_LOOSE,                     MODEL_VECTOR_SIZE(CDR_LOOSE),
        MODEL_VECTOR_OBJECT(CDR_LOOSE),                 BBOX_FILE_NAME_CDR_FULL},
    {PLAINTEXT_TABLE_CDR_SRAM_MIN,                  MODEL_VECTOR_SIZE(CDR_MIN),
        MODEL_VECTOR_OBJECT(CDR_MIN),                   BBOX_FILE_NAME_CDR_MIN},
    {PLAINTEXT_TABLE_CDR_SRAM,                      MODEL_VECTOR_SIZE(CDR_SRAM),
        MODEL_VECTOR_OBJECT(CDR_SRAM),                  BBOX_FILE_NAME_CDR_MIN},
    {PLAINTEXT_TABLE_CDR_SRAM_LOOSE,                MODEL_VECTOR_SIZE(CDR_SRAM_LOOSE),
        MODEL_VECTOR_OBJECT(CDR_SRAM_LOOSE),            BBOX_FILE_NAME_CDR_MIN},
    {PLAINTEXT_TABLE_HBM_SRAM,                      MODEL_VECTOR_SIZE(HBM_SRAM),
        MODEL_VECTOR_OBJECT(HBM_SRAM),                  BBOX_FILE_NAME_HBM},
    {PLAINTEXT_TABLE_SRAM_SNAPSHOT,                 MODEL_VECTOR_SIZE(SRAM_SNAPSHOT),
        MODEL_VECTOR_OBJECT(SRAM_SNAPSHOT),             BBOX_FILE_NAME_SRAM_SNAPSHOT},
    {PLAINTEXT_TABLE_BIOS_HISS,                     MODEL_VECTOR_SIZE(BIOS_HISS),
        MODEL_VECTOR_OBJECT(BIOS_HISS),                 BBOX_FILE_NAME_BIOS_HISS},
    {PLAINTEXT_TABLE_HBOOT,                         MODEL_VECTOR_SIZE(HBOOT),
        MODEL_VECTOR_OBJECT(HBOOT),                     BBOX_FILE_NAME_HBOOT},
    {PLAINTEXT_TABLE_MAX, 0, NULL, NULL},
};

const struct bbox_plaintext_module_map *bbox_get_module_type_map(void)
{
    return g_plaintext_module_map;
}

const struct bbox_plaintext_table_map *bbox_get_data_model_map(void)
{
    return g_plaintext_table_map;
}
