get_filename_component(SVM_SYS_CMD_DIR "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)

file(GLOB SVM_SYS_CMD_SRCS
    ${SVM_SYS_CMD_DIR}/*.c
)

list(APPEND SVM_SRC_FILES ${SVM_SYS_CMD_SRCS})
list(APPEND SVM_SRC_INC_DIRS
    ${SVM_SYS_CMD_DIR}/
)