/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * The code snippet comes from Ascend project
 *
 * Copyright (c) Huawei Technologies Co., Ltd. 2024. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "mmpa_api.h"

#ifdef __cplusplus
#if    __cplusplus
extern "C" {
#endif /* __cpluscplus */
#endif

typedef struct {
    mmEnvId id;
    const CHAR *name;
} mmEnvInfo;

static mmEnvInfo s_envList[] = {
    {MM_ENV_DUMP_GRAPH_PATH, "DUMP_GRAPH_PATH"},
    {MM_ENV_ACLNN_CACHE_LIMIT, "ACLNN_CACHE_LIMIT"},
    {MM_ENV_DISABLE_L2_CACHE, "DISABLE_L2_CACHE"},
    {MM_ENV_OPS_PRODUCT_NAME, "OPS_PRODUCT_NAME"},
    {MM_ENV_OPS_PROJECT_NAME, "OPS_PROJECT_NAME"},
    {MM_ENV_OPS_DIRECT_ACCESS_PREFIX, "OPS_DIRECT_ACCESS_PREFIX"},
    {MM_ENV_OPS_ACLNN_GEN, "OPS_ACLNN_GEN"},
    {MM_ENV_ASCEND_WORK_PATH, "ASCEND_WORK_PATH"},
    {MM_ENV_ASCEND_HOSTPID, "ASCEND_HOSTPID"},
    {MM_ENV_RANK_ID, "RANK_ID"},
    {MM_ENV_ASCEND_RT_VISIBLE_DEVICES, "ASCEND_RT_VISIBLE_DEVICES"},
    {MM_ENV_ASCEND_COREDUMP_SIGNAL, "ASCEND_COREDUMP_SIGNAL"},
    {MM_ENV_ASCEND_CACHE_PATH, "ASCEND_CACHE_PATH"},
    {MM_ENV_ASCEND_OPP_PATH, "ASCEND_OPP_PATH"},
    {MM_ENV_ASCEND_CUSTOM_OPP_PATH, "ASCEND_CUSTOM_OPP_PATH"},
    {MM_ENV_ASCEND_LOG_DEVICE_FLUSH_TIMEOUT, "ASCEND_LOG_DEVICE_FLUSH_TIMEOUT"},
    {MM_ENV_ASCEND_LOG_SAVE_MODE, "ASCEND_LOG_SAVE_MODE"},
    {MM_ENV_ASCEND_SLOG_PRINT_TO_STDOUT, "ASCEND_SLOG_PRINT_TO_STDOUT"},
    {MM_ENV_ASCEND_GLOBAL_EVENT_ENABLE, "ASCEND_GLOBAL_EVENT_ENABLE"},
    {MM_ENV_ASCEND_GLOBAL_LOG_LEVEL, "ASCEND_GLOBAL_LOG_LEVEL"},
    {MM_ENV_ASCEND_MODULE_LOG_LEVEL, "ASCEND_MODULE_LOG_LEVEL"},
    {MM_ENV_ASCEND_HOST_LOG_FILE_NUM, "ASCEND_HOST_LOG_FILE_NUM"},
    {MM_ENV_ASCEND_PROCESS_LOG_PATH, "ASCEND_PROCESS_LOG_PATH"},
    {MM_ENV_ASCEND_LOG_SYNC_SAVE, "ASCEND_LOG_SYNC_SAVE"},
    {MM_ENV_PROFILER_SAMPLECONFIG, "PROFILER_SAMPLECONFIG"},
    {MM_ENV_ACP_PIPE_FD, "ACP_PIPE_FD"},
    {MM_ENV_PROFILING_MODE, "PROFILING_MODE"},
    {MM_ENV_DYNAMIC_PROFILING_KEY_PID, "DYNAMIC_PROFILING_KEY_PID"},
    {MM_ENV_HOME, "HOME"},
    {MM_ENV_AOS_TYPE, "AOS_TYPE"},
    {MM_ENV_LD_LIBRARY_PATH, "LD_LIBRARY_PATH"},
    {MM_ENV_ASCEND_HOME_PATH, "ASCEND_HOME_PATH"},
    {MM_ENV_ASCEND_AICPU_PATH, "ASCEND_AICPU_PATH"},
    {MM_ENV_ASCEND_LATEST_INSTALL_PATH, "ASCEND_LATEST_INSTALL_PATH"},
    {MM_ENV_DATAMASTER_RUN_MODE, "DATAMASTER_RUN_MODE"},
    {MM_ENV_REGISTER_TO_ASCENDMONITOR, "REGISTER_TO_ASCENDMONITOR"},
    {MM_ENV_ASAN_RUN_MODE,"ASAN_RUN_MODE"},
    {MM_ENV_MAX_COMPILE_CORE_NUMBER, "MAX_COMPILE_CORE_NUMBER"},
    {MM_ENV_EMBEDDING_MAX_THREAD_CORE_NUMBER, "EMBEDDING_MAX_THREAD_CORE_NUMBER"},
    {MM_ENV_AICPU_PROFILING_MODE, "AICPU_PROFILING_MODE"},
    {MM_ENV_QS_RESCHED_INTEVAL, "QS_RESCHED_INTEVAL"},
    {MM_ENV_AICPU_APP_LOG_SWITCH, "AICPU_APP_LOG_SWITCH"},
    {MM_ENV_ASCEND_ENGINE_PATH, "ASCEND_ENGINE_PATH"},
    {MM_ENV_ASCEND_ENHANCE_ENABLE, "ASCEND_ENHANCE_ENABLE"},
    {MM_ENV_ASCEND_TOOLKIT_HOME, "ASCEND_TOOLKIT_HOME"},
    {MM_ENV_DUMP_GE_GRAPH, "DUMP_GE_GRAPH"},
    {MM_ENV_DUMP_GRAPH_LEVEL, "DUMP_GRAPH_LEVEL"},
    {MM_ENV_ENABLE_AUTO_FUSE, "ENABLE_AUTO_FUSE"},
    {MM_ENV_ENABLE_DYNAMIC_SHAPE_MULTI_STREAM, "ENABLE_DYNAMIC_SHAPE_MULTI_STREAM"},
    {MM_ENV_ENABLE_MBUF_ALLOCATOR, "ENABLE_MBUF_ALLOCATOR"},
    {MM_ENV_ENABLE_NETWORK_ANALYSIS_DEBUG, "ENABLE_NETWORK_ANALYSIS_DEBUG"},
    {MM_ENV_ENABLE_RUNTIME_V2, "ENABLE_RUNTIME_V2"},
    {MM_ENV_ENABLE_TILING_CACHE, "ENABLE_TILING_CACHE"},
    {MM_ENV_ESCLUSTER_CONFIG_PATH, "ESCLUSTER_CONFIG_PATH"},
    {MM_ENV_EXPERIMENTAL_ENABLE_AUTOFUSE, "EXPERIMENTAL_ENABLE_AUTOFUSE"},
    {MM_ENV_AUTOFUSE_FLAGS, "AUTOFUSE_FLAGS"},
    {MM_ENV_AUTOFUSE_DFX_FLAGS, "AUTOFUSE_DFX_FLAGS"},
    {MM_ENV_DUMP_GRAPH_FORMAT, "DUMP_GRAPH_FORMAT"},
    {MM_ENV_GE_DAVINCI_MODEL_PROFILING, "GE_DAVINCI_MODEL_PROFILING"},
    {MM_ENV_GE_PROFILING_TO_STD_OUT, "GE_PROFILING_TO_STD_OUT"},
    {MM_ENV_GE_USE_STATIC_MEMORY, "GE_USE_STATIC_MEMORY"},
    {MM_ENV_HBM_RATIO, "HBM_RATIO"},
    {MM_ENV_HELPER_RES_CONFIG, "HELPER_RES_CONFIG"},
    {MM_ENV_HELPER_RES_FILE_PATH, "HELPER_RES_FILE_PATH"},
    {MM_ENV_HELP_CLUSTER, "HELP_CLUSTER"},
    {MM_ENV_HOST_CACHE_CAPACITY, "HOST_CACHE_CAPACITY"},
    {MM_ENV_HYBRID_PROFILING_LEVEL, "HYBRID_PROFILING_LEVEL"},
    {MM_ENV_IGNORE_INFER_ERROR, "IGNORE_INFER_ERROR"},
    {MM_ENV_ITER_NUM, "ITER_NUM"},
    {MM_ENV_MAX_RUNTIME_CORE_NUMBER, "MAX_RUNTIME_CORE_NUMBER"},
    {MM_ENV_MULTI_THREAD_COMPILE, "MULTI_THREAD_COMPILE"},
    {MM_ENV_NPU_COLLECT_PATH, "NPU_COLLECT_PATH"},
    {MM_ENV_NPU_COLLECT_PATH_EXE, "NPU_COLLECT_PATH_EXE"},
    {MM_ENV_OFF_CONV_CONCAT_SPLIT, "OFF_CONV_CONCAT_SPLIT"},
    {MM_ENV_OP_NO_REUSE_MEM, "OP_NO_REUSE_MEM"},
    {MM_ENV_PROFILING_OPTIONS, "PROFILING_OPTIONS"},
    {MM_ENV_RANK_SIZE, "RANK_SIZE"},
    {MM_ENV_RESOURCE_CONFIG_PATH, "RESOURCE_CONFIG_PATH"},
    {MM_ENV_REUSE_GRAPH, "REUSE_GRAPH"},
    {MM_ENV_SKT_ENABLE, "SKT_ENABLE"},
    {MM_ENV_AUTO_USE_UC_MEMORY, "AUTO_USE_UC_MEMORY"},
    {MM_ENV_SHAREGROUP_PRECONFIG, "SHAREGROUP_PRECONFIG"},

    // HCCL
    {MM_ENV_HCCL_RDMA_PCIE_DIRECT_POST_NOSTRICT, "HCCL_RDMA_PCIE_DIRECT_POST_NOSTRICT"},
    {MM_ENV_HCCL_EXEC_TIMEOUT, "HCCL_EXEC_TIMEOUT"},
    {MM_ENV_HCCL_CONNECT_TIMEOUT, "HCCL_CONNECT_TIMEOUT"},
    {MM_ENV_HCCL_DETERMINISTIC, "HCCL_DETERMINISTIC"},
    {MM_ENV_HCCL_INTRA_PCIE_ENABLE, "HCCL_INTRA_PCIE_ENABLE"},
    {MM_ENV_HCCL_INTRA_ROCE_ENABLE, "HCCL_INTRA_ROCE_ENABLE"},
    {MM_ENV_HCCL_WHITELIST_FILE, "HCCL_WHITELIST_FILE"},
    {MM_ENV_HCCL_RDMA_QP_PORT_CONFIG_PATH, "HCCL_RDMA_QP_PORT_CONFIG_PATH"},
    {MM_ENV_HCCL_WHITELIST_DISABLE, "HCCL_WHITELIST_DISABLE"},
    {MM_ENV_HCCL_IF_BASE_PORT, "HCCL_IF_BASE_PORT"},
    {MM_ENV_HCCL_IF_IP, "HCCL_IF_IP"},
    {MM_ENV_HCCL_SOCKET_FAMILY, "HCCL_SOCKET_FAMILY"},
    {MM_ENV_HCCL_SOCKET_IFNAME, "HCCL_SOCKET_IFNAME"},
    {MM_ENV_HCCL_ALGO, "HCCL_ALGO"},
    {MM_ENV_HCCL_RDMA_TC, "HCCL_RDMA_TC"},
    {MM_ENV_HCCL_RDMA_SL, "HCCL_RDMA_SL"},
    {MM_ENV_HCCL_RDMA_TIMEOUT, "HCCL_RDMA_TIMEOUT"},
    {MM_ENV_HCCL_RDMA_RETRY_CNT, "HCCL_RDMA_RETRY_CNT"},
    {MM_ENV_HCCL_BUFFSIZE, "HCCL_BUFFSIZE"},
    {MM_ENV_HCCL_DIAGNOSE_ENABLE, "HCCL_DIAGNOSE_ENABLE"},
    {MM_ENV_HCCL_RDMA_QPS_PER_CONNECTION, "HCCL_RDMA_QPS_PER_CONNECTION"},
    {MM_ENV_HCCL_MULTI_QP_THRESHOLD, "HCCL_MULTI_QP_THRESHOLD"},
    {MM_ENV_HCCL_ENTRY_LOG_ENABLE, "HCCL_ENTRY_LOG_ENABLE"},
    {MM_ENV_HCCL_OP_EXPANSION_MODE, "HCCL_OP_EXPANSION_MODE"},
    {MM_ENV_HCCL_INTER_HCCS_DISABLE, "HCCL_INTER_HCCS_DISABLE"},
    {MM_ENV_HCCL_DEBUG_CONFIG, "HCCL_DEBUG_CONFIG"},
    {MM_ENV_HCCL_OP_RETRY_ENABLE, "HCCL_OP_RETRY_ENABLE"},
    {MM_ENV_HCCL_CONCURRENT_ENABLE, "HCCL_CONCURRENT_ENABLE"},
    {MM_ENV_HCCL_OP_RETRY_PARAMS, "HCCL_OP_RETRY_PARAMS"},
    {MM_ENV_HCCL_LOGIC_SUPERPOD_ID, "HCCL_LOGIC_SUPERPOD_ID"},
    {MM_ENV_HCCL_HOST_SOCKET_PORT_RANGE, "HCCL_HOST_SOCKET_PORT_RANGE"},
    {MM_ENV_HCCL_NPU_SOCKET_PORT_RANGE, "HCCL_NPU_SOCKET_PORT_RANGE"},
    {MM_ENV_HCCL_DFS_CONFIG, "HCCL_DFS_CONFIG"},

    // AOE
    {MM_ENV_TUNE_BANK_PATH, "TUNE_BANK_PATH"},
    
    // FE
    {MM_ENV_ENABLE_ACLNN, "ENABLE_ACLNN"},
    {MM_ENV_MIN_COMPILE_RESOURCE_USAGE_CTRL, "MIN_COMPILE_RESOURCE_USAGE_CTRL"},
    {MM_ENV_OP_DYNAMIC_COMPILE_STATIC, "OP_DYNAMIC_COMPILE_STATIC"},

    // TE
    {MM_ENV_ASCEND_MAX_OP_CACHE_SIZE, "ASCEND_MAX_OP_CACHE_SIZE"},
    {MM_ENV_ASCEND_REMAIN_CACHE_SIZE_RATIO, "ASCEND_REMAIN_CACHE_SIZE_RATIO"},
    {MM_ENV_ASCEND_OP_COMPILER_WORK_PATH_IN_KERNEL_META, "ASCEND_OP_COMPILER_WORK_PATH_IN_KERNEL_META"},
    {MM_ENV_TE_PARALLEL_COMPILER, "TE_PARALLEL_COMPILER"},
    {MM_ENV_TEFUSION_NEW_DFXINFO, "TEFUSION_NEW_DFXINFO"},
    {MM_ENV_TE_AUTO_RESTART_COUNTER, "TE_AUTO_RESTART_COUNTER"},
    {MM_ENV_PYTHONPATH, "PYTHONPATH"},
    {MM_ENV_PARA_DEBUG_PATH, "PARA_DEBUG_PATH"},
    {MM_ENV_PATH, "PATH"},
    {MM_ENV_CONTEXT_MODELCOMPILING, "CONTEXT_MODELCOMPILING"},

    // AMCT
    {MM_ENV_AMCT_LOG_DUMP, "AMCT_LOG_DUMP"},
    // RUNTIME
    {MM_ENV_CAMODEL_LOG_PATH, "CAMODEL_LOG_PATH"},

};

static mmEnvInfo *GetEnvInfoById(mmEnvId id)
{
    ULONG i = 0;
    for (i = 0; i < sizeof(s_envList)/sizeof(s_envList[0]); ++i) {
        if (s_envList[i].id == id) {
            return &s_envList[i];
        }
    }
    return NULL;
}

/*
 * 描述:通过id获取环境变量
 * 参数:id --环境变量枚举值
 * 返回值:执行成功返回内指针, 执行错误返回NULL
 */
CHAR *mmSysGetEnv(mmEnvId id)
{
    mmEnvInfo *envInfo = GetEnvInfoById(id);
    if (NULL != envInfo) {
        return getenv(envInfo->name);
    }
    return NULL;
}

/*
 * 描述:通过id设置环境变量
 * 参数:id --环境变量枚举值
 *      value -- 由用户分配用来存放环境变量的缓存
 *      overwrite -- 是否覆盖标志位 0 表示不覆盖
 * 返回值:执行成功返回EN_OK, 执行错误返回EN_ERROR, 入参检查错误返回EN_INVALID_PARAM
 */
INT32 mmSysSetEnv(mmEnvId id, const CHAR *value, INT32 overwrite)
{
    mmEnvInfo *envInfo = GetEnvInfoById(id);
    if (NULL == envInfo) {
        return EN_INVALID_PARAM;
    }
    return setenv(envInfo->name, value, overwrite);
}

/*
 * 描述:通过id删除环境变量
 * 参数:id --环境变量枚举值
 * 返回值:执行成功返回EN_OK, 执行错误返回EN_ERROR, 入参检查错误返回EN_INVALID_PARAM
 */
INT32 mmSysUnsetEnv(mmEnvId id)
{
    mmEnvInfo *envInfo = GetEnvInfoById(id);
    if (NULL == envInfo) {
        return EN_INVALID_PARAM;
    }
    return unsetenv(envInfo->name);
}

/*
 * 描述:获取环境变量
 * 参数:name --需要获取的环境变量名
 *      len --缓存长度,
 *      value -- 由用户分配用来存放环境变量的缓存
 * 返回值:执行成功返回EN_OK, 执行错误返回EN_ERROR, 入参检查错误返回EN_INVALID_PARAM
 */
INT32 mmGetEnv(const CHAR *name, CHAR *value, UINT32 len)
{
    INT32 ret;
    UINT32 envLen = 0;
    if ((name == NULL) || (value == NULL) || (len == MMPA_ZERO)) {
        return EN_INVALID_PARAM;
    }
    const CHAR *envPtr = getenv(name);
    if (envPtr == NULL) {
        return EN_ERROR;
    }

    UINT32 lenOfRet = (UINT32)strlen(envPtr);
    if (lenOfRet < (UINT32)(MMPA_MEM_MAX_LEN - 1)) {
        envLen = lenOfRet + 1U;
    }

    if ((envLen != MMPA_ZERO) && (len < envLen)) {
        return EN_INVALID_PARAM;
    } else {
        ret = memcpy_s(value, len, envPtr, envLen); //lint !e613
        if (ret != EN_OK) {
            return EN_ERROR;
        }
    }
    return EN_OK;
}

/*
 * 描述:设置环境变量
 * 参数:name --需要获取的环境变量名
 *      value -- 由用户分配用来存放环境变量的缓存
 *      overwrite -- 是否覆盖标志位 0 表示不覆盖
 * 返回值:执行成功返回EN_OK, 执行错误返回EN_ERROR, 入参检查错误返回EN_INVALID_PARAM
 */
INT32 mmSetEnv(const CHAR *name, const CHAR *value, INT32 overwrite)
{
    if ((name == NULL) || (value == NULL)) {
        return EN_INVALID_PARAM;
    }

    return setenv(name, value, overwrite);
}

#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cpluscplus */
#endif /* __cpluscplus */
