/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */

#ifndef PBL_URD_MAIN_CMD_DEF_H
#define PBL_URD_MAIN_CMD_DEF_H
#include "dev_mon_cmd_def.h"

#define MAKE_UP_DAVINCI_COMMAND(cmd)  ((DEV_MON_SMB_FUN_CODE_DAVINCI << 16) | (cmd))
#define MAKE_UP_COMMON_COMMAND(cmd)  ((DEV_MON_SMB_FUN_CODE_COMMON << 16) | (cmd))

/* main cmd is 0 : 0xffffffff */
enum urd_main_cmd {
    /* dmp common cmd, start from 0x0  */
    DMS_GET_HEALTH_CMD      = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_HEALTH_STATE),     /* 0x1 */
    DMS_GET_ERR_CODE_CMD    = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_ERROR_CODE),       /* 0x2 */
    DMS_GET_CHIP_TEMP_CMD   = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_CHIP_TEMP),        /* 0x3 */
    DMS_GET_POWER_CMD       = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_POWER),            /* 0x4 */
    DMS_GET_PCIE_VID_CMD    = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_VID),              /* 0x6 */  
    DMS_GET_PCIE_DID_CMD    = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_DID),              /* 0x7 */
    DMS_GET_PCIE_SUBVID_CMD = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_SUBVID),           /* 0x9 */
    DMS_GET_PCIE_SUBDID_CMD = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_SUBDID),           /* 0xA */ 
    DMS_GET_CHIP_VOLT_CMD   = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_CHIP_VOLT),        /* 0xB */
    DMS_GET_BOARD_ID_CMD    = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_GET_BOARD_ID),         /* 0xF */
    DMS_GET_ECC_STAT_CMD    = MAKE_UP_COMMON_COMMAND(DEV_MON_CMD_QUERY_ECC_STAT),       /* 0x1F */

    /* feature customization */
    DMS_MAIN_CMD_BASIC      = 'E',   /* 0x45 */
    DMS_MAIN_CMD_SOC        = 'F',
    DMS_MAIN_CMD_MEMORY     = 'G',
    DMS_MAIN_CMD_LPM        = 'H',
    DMS_MAIN_CMD_PRODUCT    = 'I',
    DMS_MAIN_CMD_SOFT_FAULT = 'J',
    DMS_MAIN_CMD_TRS        = 'K',
    DMS_MAIN_CMD_SENSORHUB  = 'L',
    DMS_MAIN_CMD_ISP        = 'M',
    DMS_MAIN_CMD_CAN        = 'N',
    DMS_MAIN_CMD_BBOX       = 'O',
    DMS_MAIN_CMD_EMMC       = 'P',
    DMS_MAIN_CMD_PCIE       = 'Q',
    DMS_MAIN_CMD_QOS        = 'R',
    DMS_MAIN_CMD_LOG        = 'S',
    DMS_MAIN_CMD_CAPA_GROUP = 'T',
    ASCEND_UB_CMD_BASIC     = 'U',
    DMS_MAIN_CMD_IMU        = 'V',
    DMS_MAIN_CMD_SILS       = 'w',
    DMS_MAIN_CMD_P2P_COM    = 'X',
    DMS_MAIN_CMD_FLASH      = 'Y',
    URD_TRS_MODE_CONFIG_CMD = 'Z',
    URD_TRS_MODE_QUERY_CMD  = '[',
    DMS_MAIN_CMD_HOTRESET   = ']',
    DMS_MAIN_CMD_DVPP = 0x60000,

    /* dmp davinci cmd, start from  0x60001 */
    DMS_GET_D_INFO_CMD                  = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_D_INFO),              /* 0x60005 */
    DMS_GET_FLASH_INFO_CMD              = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_FLASH_D_INFO),        /* 0x60006 */

    DMS_GET_SENSOR_INFO_CMD             = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_MINI_SENSOR_INFO),      /* 0x60011 */
    DMS_GET_GET_USER_CONFIG_CMD         = MAKE_UP_DAVINCI_COMMAND(DMP_MON_CMD_GET_USER_CONFIG),
    DMS_GET_SET_USER_CONFIG_CMD         = MAKE_UP_DAVINCI_COMMAND(DMP_MON_CMD_SET_USER_CONFIG),
    DMS_GET_CNTPCT_CMD                  = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_CNTPCT),
    DMS_GET_GET_ERRSTR_CMD              = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_ERRSTR),
    DMS_GET_GET_LLC_PERF_PARA           = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_LLC_PERF_PARA),
    DMS_GET_NETWORK_HEALTH_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_NETWORK_HEALTH),
    DMS_GET_ISOLATED_PAGES_INFO_CMD     = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_ISOLATED_PAGES_INFO),
    DMS_CLEAR_ISOLATED_INFO_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_CLEAR_ISOLATED_INFO),
    DMS_GET_MULTI_ECC_TIME_INFO_CMD     = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_MULTI_ECC_TIME_INFO),
    DMS_GET_ECC_RECORD_CMD              = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_ECC_RECORD_INFO),
    DMS_GET_GET_DIE_ID_CMD              = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_DIE_ID),
    DMS_GET_GET_NET_DEV_INFO_CMD        = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_NET_DEV_INFO),
    DMS_GET_GET_AICPU_INFO_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_AICPU_INFO),
    DMS_GET_SET_REVOCATION_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_REVOCATION),
    DMS_GET_GET_DEVICE_INFO_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_DEVICE_INFO),
    DMS_GET_SET_DEVICE_INFO_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_DEVICE_INFO),
    DMS_GET_GET_REBOOT_REASON_CMD       = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_REBOOT_REASON),
    DMS_GET_BIST_INFO_CMD               = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_BIST_INFO),
    DMS_CTRL_DEVICE_NODE_CMD            = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_CTRL_DEVICE_NODE),
    DMS_GET_ALL_DEVICE_NODE_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_ALL_DEVICE_NODE),
    DMS_SET_BIST_INFO_CMD               = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_BIST_INFO),
    DMS_FAULT_INJECT_CMD                = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_FAULT_INJECT),

    DMS_CREATE_CAPABILITY_GROUP_CMD     = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_CREATE_CAPABILITY_GROUP),
    DMS_DELETE_CAPABILITY_GROUP_CMD     = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_DELETE_CAPABILITY_GROUP),
    DMS_GET_CAPABILITY_GROUP_INFO_CMD   = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_CAPABILITY_GROUP_INFO),
    DMS_GET_LAST_BOOTSTATE_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_LAST_BOOTSTATE),
    DMS_GET_GET_HISSSTATUS_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_HISSSTATUS),
    DMS_GET_GET_LPSTATUS_CMD            = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_LPSTATUS),
    DMS_GET_SET_POWER_STATE_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_POWER_STATE),
    DMS_GET_GET_CAN_STATUS_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_CAN_STATUS),
    DMS_GET_GET_UFS_STATUS_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_UFS_STATUS),
    DMS_GET_GET_SENSORHUB_STATUS_CMD    = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_SENSORHUB_STATUS),
    DMS_GET_GET_UFS_CONFIG_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_UFS_CONFIG),
    DMS_GET_SET_UFS_CONFIG_CMD          = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_UFS_CONFIG),
    DMS_GET_GET_SENSORHUB_CONFIG_CMD    = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_SENSORHUB_CONFIG),
    DMS_GET_GET_GPIO_STATUS_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_GPIO_STATUS),
    DMS_GET_GET_SOC_HW_FAULT_CMD        = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_SOC_HW_FAULT),
    DMS_GET_GET_SAFETYISLAND_STATUS_CMD = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_SAFETYISLAND_STATUS),
    DMS_GET_GET_EMMC_INFO_CMD           = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_EMMC_INFO),

    DMS_GET_CHIP_EXPAND_VERSION_CMD     = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_CHIP_EXPAND_VERSION), /* 0x6009E */
    DMS_GET_SET_DETECT_INFO_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_DETECT_INFO),
    DMS_GET_GET_DETECT_INFO_CMD         = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_DETECT_INFO),
    DMS_GET_FLASH_CONTENT               = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_GET_FLASH_CONTENT),
    DMS_SET_FLASH_CONTENT               = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_D_SET_FLASH_CONTENT),
    DMS_GET_UDIS_DEVICE_INFO_CMD        = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_GET_UDIS_DEVICE_INFO),
    DMS_SET_UDIS_DEVICE_INFO_CMD        = MAKE_UP_DAVINCI_COMMAND(DEV_MON_CMD_SET_UDIS_DEVICE_INFO),
};

#endif
