# ------------------------------------------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ------------------------------------------------------------------------------------------------------------

# ==== devmng ====
EXTRA_CFLAGS += -DCFG_FEATURE_KA
EXTRA_CFLAGS += -DCFG_FEATURE_DEV_TOPOLOGY
EXTRA_CFLAGS += -DCFG_FEATURE_CHIP_INFO_FROM_DEVINFO
EXTRA_CFLAGS += -DCFG_FEATURE_GET_CURRENT_EVENTINFO
EXTRA_CFLAGS += -DCFG_FEATURE_KA_ALLOC_INTERFACE
EXTRA_CFLAGS += -DCFG_FEATURE_HEALTH_ERR_CODE
EXTRA_CFLAGS += -DCFG_FEATURE_NEW_EVENT_CODE
EXTRA_CFLAGS += -DCFG_FEATURE_ERRORCODE_ON_NEW_CHIPS
EXTRA_CFLAGS += -DCFG_FEATURE_TRS_HB_REFACTOR
EXTRA_CFLAGS += -DCFG_FEATURE_UDIS
EXTRA_CFLAGS += -DCFG_FEATURE_PG
EXTRA_CFLAGS += -DCFG_FEATURE_VFG
EXTRA_CFLAGS += -DCFG_FEATURE_SRIOV
EXTRA_CFLAGS += -DCFG_FEATURE_TOPOLOGY_BY_HCCS_LINK_STATUS
EXTRA_CFLAGS += -DCFG_FEATURE_SUPPORT_GET_SPOD_PING_INFO

# bbox
EXTRA_CFLAGS += -DCFG_FEATURE_LOG_DUMP_FROM_PCIE

# chip_dev

# core

# custom
EXTRA_CFLAGS += -DCFG_FEATURE_CUST_OP_ENHANCE

# event

# hccs

# heart_beat
EXTRA_CFLAGS += -DCFG_FEATURE_HEART_BEAT
EXTRA_CFLAGS += -DCFG_FEATURE_HEARTBEAT_CNT_PCIE

# hotreset

# log

# status

# time
EXTRA_CFLAGS += -DCFG_FEATURE_TIMESYNC

# ub

# urd_forward
EXTRA_CFLAGS += -DCFG_FEATURE_SDK_EX_VERSION
EXTRA_CFLAGS += -DCFG_FEATURE_QUERY_FREQ_INFO
EXTRA_CFLAGS += -DCFG_FEATURE_QUERY_QOS_CFG_INFO
EXTRA_CFLAGS += -DCFG_FEATURE_QUERY_VA_INFO

# drv_devmng
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD_HOST
EXTRA_CFLAGS += -DCFG_FEATURE_VASCEND
EXTRA_CFLAGS += -DCFG_FEATURE_BBOX_KDUMP
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD_V2
EXTRA_CFLAGS += -DCFG_FEATURE_CHIP_DIE
EXTRA_CFLAGS += -DCFG_FEATURE_PCIE_BBOX_ADDR
EXTRA_CFLAGS += -DCFG_FEATURE_VF_USE_DEVID
EXTRA_CFLAGS += -DCFG_FEATURE_VDEV_MEMORY_FROM_DEVMNG_H2D
EXTRA_CFLAGS += -DCFG_FEATURE_BIND_TGID
EXTRA_CFLAGS += -DCFG_FEATURE_VFIO
EXTRA_CFLAGS += -DCFG_FEATURE_SHARE_LOG
EXTRA_CFLAGS += -DCFG_FEATURE_PCIE_HOST_DEVICE_COMM
EXTRA_CFLAGS += -DCFG_FEATURE_HOST_LOG
EXTRA_CFLAGS += -DCFG_FEATURE_INUSE_NUM_DYNAMIC
EXTRA_CFLAGS += -DCFG_FEATURE_ADMIN_CONTAINER_PID

# qos
EXTRA_CFLAGS += -DCFG_FEATURE_GET_QOS_MASTER_CFG

