# ------------------------------------------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ------------------------------------------------------------------------------------------------------------

ifeq ($(ENABLE_UBE), true)
	EXTRA_CFLAGS += -DCFG_FEATURE_UB
endif

# ==== devmng ====
EXTRA_CFLAGS += -DCFG_FEATURE_PCIE_HOST_DEVICE_COMM
EXTRA_CFLAGS += -DCFG_FEATURE_KA
EXTRA_CFLAGS += -DCFG_FEATURE_DEV_TOPOLOGY
EXTRA_CFLAGS += -DCFG_FEATURE_CHIP_INFO_FROM_DEVINFO
EXTRA_CFLAGS += -DCFG_FEATURE_USE_ADPATER_FUNC
EXTRA_CFLAGS += -DCFG_FEATURE_GET_CURRENT_EVENTINFO
EXTRA_CFLAGS += -DCFG_FEATURE_D2D_UB
EXTRA_CFLAGS += -DCFG_FEATURE_ASCEND950_FPGA_STUB
EXTRA_CFLAGS += -DCFG_FEATURE_PG
EXTRA_CFLAGS += -DCFG_FEATURE_VFG
EXTRA_CFLAGS += -DCFG_FEATURE_TOPOLOGY_BY_SMP
EXTRA_CFLAGS += -DCFG_FEATURE_UB_HOST_DEVICE_COMM
EXTRA_CFLAGS += -DCFG_FEATURE_SRIOV
EXTRA_CFLAGS += -DCFG_FEATURE_ASCEND950_API_ADAPT_STUB
EXTRA_CFLAGS += -DCFG_FEATURE_AIC_ERRMAP_BY_PG
EXTRA_CFLAGS += -DCFG_FEATURE_TRS_HB_REFACTOR
EXTRA_CFLAGS += -DCFG_FEATURE_AICORE_DIE_NUM
EXTRA_CFLAGS += -DCFG_FEATURE_CPU_WORK_MODE_CONFIG
EXTRA_CFLAGS += -DCFG_FEATURE_CHASSIS
EXTRA_CFLAGS += -DCFG_FEATURE_NEW_EVENT_CODE
EXTRA_CFLAGS += -DCFG_FEATURE_COM_CPU_CONFIG

# bbox

# bbox_dump
EXTRA_CFLAGS += -DDRV_HOST
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD_V4
EXTRA_CFLAGS += -DCFG_FEATURE_PCIE_BBOX_DUMP

# chip_dev

# core

# custom

# event

# hccs

# heart_beat
EXTRA_CFLAGS += -DCFG_FEATURE_HEART_BEAT

# hotreset
EXTRA_CFLAGS += -DCFG_FEATURE_SUPPORT_HOTRESET_AO_INFORM

# log

# status
EXTRA_CFLAGS += -DCFG_FEATURE_FREQ_ACCURACY_5_PERCENT

# time
EXTRA_CFLAGS += -DCFG_FEATURE_TIMESYNC
# ub

# urd_forward
EXTRA_CFLAGS += -DCFG_FEATURE_SDK_EX_VERSION
EXTRA_CFLAGS += -DCFG_FEATURE_QUERY_FREQ_INFO
EXTRA_CFLAGS += -DCFG_FEATURE_QUERY_QOS_CFG_INFO
EXTRA_CFLAGS += -DCFG_FEATURE_QUERY_VA_INFO

# drv_devmng
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD_HOST
EXTRA_CFLAGS += -DCFG_FEATURE_VASCEND
EXTRA_CFLAGS += -DCFG_FEATURE_UB_HOST_DEVICE_COMM
EXTRA_CFLAGS += -DCFG_FEATURE_ASCEND950_STUB
EXTRA_CFLAGS += -DCFG_FEATURE_BIOS_HW_INFO_BY_SOC_RES
EXTRA_CFLAGS += -DCFG_FEATURE_PG_INFO_BY_SOC_RESMNG
EXTRA_CFLAGS += -DCFG_FEATURE_REFACTOR
EXTRA_CFLAGS += -DCFG_FEATURE_SHM_DEVMNG
EXTRA_CFLAGS += -DCFG_FEATURE_PRODUCT_TYPE_BY_SOC_RES
EXTRA_CFLAGS += -DCFG_FEATURE_PCIE_BBOX_DUMP
EXTRA_CFLAGS += -DCFG_SOC_PLATFORM_CLOUD_V2
EXTRA_CFLAGS += -DCFG_FEATURE_CHIP_DIE
EXTRA_CFLAGS += -DCFG_FEATURE_PCIE_BBOX_ADDR
EXTRA_CFLAGS += -DCFG_FEATURE_VF_USE_DEVID
EXTRA_CFLAGS += -DCFG_FEATURE_VDEV_MEMORY_FROM_DEVMNG_H2D
EXTRA_CFLAGS += -DCFG_FEATURE_BIND_TGID
EXTRA_CFLAGS += -DCFG_FEATURE_GET_CURRENT_EVENTINFO
EXTRA_CFLAGS += -DCFG_FEATURE_VFIO
EXTRA_CFLAGS += -DCFG_FEATURE_SHARE_LOG
EXTRA_CFLAGS += -DCFG_FEATURE_HOST_LOG
EXTRA_CFLAGS += -DCFG_FEATURE_APM_SUPP_PID
EXTRA_CFLAGS += -DCFG_FEATURE_PM
EXTRA_CFLAGS += -DCFG_FEATURE_INUSE_NUM_DYNAMIC
EXTRA_CFLAGS += -DCFG_FEATURE_GET_DEV_INDEX_IN_GROUP
