/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef __DSMI_DFT_CMD_INFO_DEF_H__
#define __DSMI_DFT_CMD_INFO_DEF_H__

#include "dsmi_dmp_command.h"
#include "dsmi_dft_common.h"
#include "dev_mon_iam_type.h"

DSMI_CMD_DEF_COMMON_INSTANCE(DEV_MON_CMD_WRITE_CLEAR_LABEL_DATA, CMD_LENGTH_INVALID, 0, UNDEFINED_TYPE)
DSMI_CMD_DEF_COMMON_INSTANCE(DEV_MON_CMD_DFT_CONTROL, 1, sizeof(unsigned int), UNDEFINED_TYPE)
DSMI_CMD_DEF_COMMON_INSTANCE(DEV_MON_CMD_GET_DFT_STATE, 1, sizeof(DSMI_GET_DFT_STATE_RES), UNDEFINED_TYPE)
DSMI_CMD_DEF_COMMON_INSTANCE(DEV_MON_CMD_SET_AGING_FLAG_TIME, (sizeof(DSMI_AGING_CODE) + sizeof(DSMI_AGINE_DATA)), 0,
                             UNDEFINED_TYPE)
DSMI_CMD_DEF_COMMON_INSTANCE(DEV_MON_CMD_GET_AGING_FLAG_TIME, sizeof(DSMI_AGING_CODE), sizeof(DSMI_AGINE_DATA),
                             UNDEFINED_TYPE)
DSMI_CMD_DEF_COMMON_INSTANCE(DEV_MON_CMD_GET_AGING_RESULT, sizeof(DSMI_AGING_CODE), sizeof(DSMI_AGING_RESULT_DATA),
                             UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_GET_PMU_DIE_ID, sizeof(unsigned char), sizeof(DSMI_DIE_ID), UNDEFINED_TYPE)

/* DAVINCI COMMAND DEF */
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_D_LOAD_DFT_TEST_LIB, sizeof(DSMI_TEST_LIB), 0, UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_DFT_FW_LOAD, CMD_LENGTH_INVALID, 0, UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DMP_LSB_OP_CODE_DFT_STRESS_TEST, CMD_LENGTH_INVALID, 0, UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_SET_EFUSE_INFO, CMD_LENGTH_INVALID, 0, UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_CHECK_EFUSE_INFO, CMD_LENGTH_INVALID, 0, UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_DEBUG_SEND_DATA, CMD_LENGTH_INVALID, CMD_LENGTH_INVALID, UNDEFINED_TYPE)

DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_D_GET_PMU_VOLTAGE, (sizeof(unsigned char) + sizeof(unsigned char)),
                              sizeof(unsigned int), UNDEFINED_TYPE)
DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_MON_CMD_GET_CNTPCT, 0, CMD_LENGTH_INVALID, UNDEFINED_TYPE)

DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_EQUIP_CMD_D_SET_DEVICE_INFO, CMD_LENGTH_INVALID,
                              CMD_LENGTH_INVALID, STATE_MANAGE_TYPE)

DSMI_CMD_DEF_DAVINCI_INSTANCE(DEV_EQUIP_CMD_D_GET_DEVICE_INFO, CMD_LENGTH_INVALID,
                              CMD_LENGTH_INVALID, STATE_MANAGE_TYPE)

#endif
