/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */

#ifndef __DMS_PRODUCT_IOCTL_H__
#define __DMS_PRODUCT_IOCTL_H__

#define DMS_PRODUCT_CMD_NAME "DMS_PRODUCT_CMD_NAME"
#define DMS_SUBCMD_GET_PCIE_ID_INFO_ALL 0
#define DMS_SUBCMD_GET_WORK_MODE 1
// DMS_SUBCMD_GET_VRD_INFO 2 in turing
#define DMS_SUBCMD_GET_PCIE_BANDWIDTH_INFO 3
#define DMS_SUBCMD_GET_HBM_MANUFACTURER_ID 4
#define DMS_SUBCMD_GET_MAINBOARD_ID 5
#define DMS_SUBCMD_GET_HCCS_STATUS 6
#define DMS_SUBCMD_GET_HCCS_BANDWIDTH_INFO 7
#define DMS_SUBCMD_GET_HCCS_LINK_ERROR_INFO 8
#define DMS_SUBCMD_GET_PCIE_LINK_ERROR_INFO 9

#endif